const { app, BrowserWindow } = require('electron')
const assert = require('node:assert/strict')
const fsSync = require('node:fs')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const { randomUUID } = require('node:crypto')
const Module = require('node:module')

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
const timeout = setTimeout(() => { console.error('UI smoke timed out'); app.exit(1) }, 45000)
const root = fsSync.mkdtempSync(path.join(os.tmpdir(), 'omnishell-ui-'))
process.env.OMNISHELL_DISABLE_AUTO_UPDATE = '1'
process.env.OMNISHELL_SYSTEM_ROOT = path.join(root, 'system')
app.setPath('userData', path.join(root, 'userdata'))
const errors = []

;(async () => {
  // Exercise the real renderer, preload, IPC and ConPTY without visible test windows.
  BrowserWindow.prototype.show = function () {}
  BrowserWindow.prototype.showInactive = function () {}
  const executable = path.join(root, 'system/Codex/node_modules/.bin/codex.cmd')
  await fs.mkdir(path.dirname(executable), { recursive: true })
  await fs.writeFile(executable, '@echo off\r\necho OMNISHELL_TEST_READY\r\nset /p reply=\r\n', 'utf8')
  await fs.mkdir(path.join(root, 'system/Codex/Profiles/Default'), { recursive: true })
  await fs.writeFile(path.join(root, 'system/Codex/Profiles/Default/profile.json'), '{"id":"default"}', 'utf8')
  app.on('web-contents-created', (_event, contents) => {
    contents.setBackgroundThrottling(false)
    contents.on('console-message', (event) => {
      if (event.level === 'error' || event.level === 3) errors.push(event.message)
    })
  })
  const load = Module._load
  Module._load = function (name, parent, ...args) {
    const result = load.call(this, name, parent, ...args)
    if (name !== 'electron') return result
    return { ...result, BrowserWindow: class extends BrowserWindow {
      constructor(options) {
        super({ ...options, webPreferences: { ...options.webPreferences, offscreen: true, backgroundThrottling: false } })
      }
    } }
  }
  try { require('../main') } finally { Module._load = load }
  await app.whenReady()
  let win
  for (let attempt = 0; attempt < 100; attempt += 1) {
    win = BrowserWindow.getAllWindows()[0]
    if (win && !win.webContents.isLoading()) {
      const ready = await win.webContents.executeJavaScript('typeof tools !== "undefined" && tools.length === 12 && bootScreen.classList.contains("hidden")').catch(() => false)
      if (ready) break
    }
    await delay(50)
  }
  assert.ok(win, 'main window created')
  const js = (code) => win.webContents.executeJavaScript(code)
  assert.equal(await js('tools.length'), 12)
  assert.equal(await js('gridColumns()'), 1)
  assert.ok(await js('listScroll.getBoundingClientRect().right < brandStage.getBoundingClientRect().right'), 'tool list is left of the wordmark')
  assert.deepEqual(await js('[rows.get("claude").item.dataset.distance, rows.get("codex").item.dataset.distance, rows.get("opencode").item.dataset.distance]'), ['0', '1', '2'])
  assert.ok(await js('rows.get("claude").item.getBoundingClientRect().width > rows.get("codex").item.getBoundingClientRect().width'), 'selected item is prominent')
  await js('selectTool("codex", true)')
  await delay(240)
  assert.deepEqual(await js('[rows.get("claude").item.dataset.distance, rows.get("codex").item.dataset.distance, rows.get("opencode").item.dataset.distance]'), ['1', '0', '1'])
  const carouselCost = await js('(() => { const start=performance.now(); for(let index=0;index<200;index++) selectTool(tools[index%tools.length].id); return {elapsed:performance.now()-start, frame:carouselFrame} })()')
  assert.ok(carouselCost.elapsed < 50, `selection updates took ${carouselCost.elapsed}ms`)
  assert.notEqual(carouselCost.frame, 0, 'selection updates share one animation frame')
  await js('selectTool("codex", true)')
  await delay(240)
  const outputDir = path.resolve(__dirname, '../../out/review')
  await fs.mkdir(outputDir, { recursive: true })
  await fs.writeFile(path.join(outputDir, 'focus-carousel.png'), (await win.webContents.capturePage()).toPNG())
  const viewAnimation = js('(() => { const pending=showView("terminal"); window.__viewTransitionActive=viewTerminal.getAnimations().length>0; return pending.then(()=>window.__viewTransitionActive) })()')
  assert.equal(await viewAnimation, true, 'opening the terminal uses the view transition')
  await js('showView("list", true)')
  await js('openTerminal(getTool("codex"))')
  for (let attempt = 0; attempt < 100; attempt += 1) {
    if (await js('terminal.buffer.active.getLine(0)?.translateToString().includes("OMNISHELL_TEST_READY")')) break
    await delay(30)
  }
  assert.equal(await js('terminalExited'), false)
  await js('showContextMenu(600, 300); ctxOpenOther.dispatchEvent(new PointerEvent("pointerenter")); ctxOpenOther.click()')
  await delay(200)
  assert.equal(await js('getComputedStyle(ctxSubMenu).display'), 'block', 'hover followed by click keeps Switch CLI open')
  const menuBounds = await js('(() => { const r = ctxSubMenu.getBoundingClientRect(); return { top: r.top, bottom: r.bottom, right: r.right, left: r.left, height: innerHeight, width: innerWidth } })()')
  assert.ok(menuBounds.top >= 0 && menuBounds.bottom <= menuBounds.height && menuBounds.left >= 0 && menuBounds.right <= menuBounds.width, `submenu fits in window: ${JSON.stringify(menuBounds)}`)
  await fs.writeFile(path.join(outputDir, 'switch-cli.png'), (await win.webContents.capturePage()).toPNG())
  await js('ctxSubMenu.querySelector("[data-tool-id=opencode]").click()')
  await delay(100)
  assert.equal(await js('profileDialogToolId'), 'opencode', 'Switch CLI opens the selected profile picker')
  assert.equal(BrowserWindow.getAllWindows().length, 1)
  await js('closeProfilePicker(true); hideContextMenu(); clearTerminalSurface()')
  await js('new Promise(resolve => terminal.write("\\x1b[48;2;160;20;20m" + " ".repeat(terminal.cols * terminal.rows) + "\\x1b[0m", resolve))')
  await js('paintTerminalEdges()')
  assert.equal(await js('terminalSurfaceColor'), '#000000', 'diff background cannot recolor the terminal surface')
  await js('new Promise(resolve => { let data="\\x1b[2J"; for(let row=1;row<=terminal.rows;row++) data += "\\x1b["+row+";1H\\x1b[48;2;32;31;39m"+" ".repeat(terminal.cols); terminal.write(data+"\\x1b[0m", resolve) })')
  await js('paintTerminalEdges()')
  assert.equal(await js('terminal.options.theme.background'), '#000000', 'neutral gray cells do not change the theme')
  const bottom = await js('Array.from($("terminal-edges").getContext("2d").getImageData(Math.floor($("terminal-edges").width/2),$("terminal-edges").height-1,1,1).data)')
  assert.deepEqual(bottom, [32,31,39,255], 'bottom padding matches the actual terminal edge')
  await js('new Promise(resolve => terminal.write("\\r\\n".repeat(150), resolve))')
  const scrollbarWidth = await js('parseFloat(getComputedStyle(terminal.element.querySelector(".scrollbar.vertical")).width)')
  assert.ok(scrollbarWidth <= 5.1, 'terminal scrollbar remains narrow')
  assert.ok(await js('(() => { const screen=terminal.element.querySelector(".xterm-screen"),r=screen.getBoundingClientRect(); for(let p=screen.parentElement;p && p!==viewTerminal;p=p.parentElement){const b=p.getBoundingClientRect(),s=getComputedStyle(p);if(["hidden","clip"].includes(s.overflowX) && r.right>b.right+1)return false;if(["hidden","clip"].includes(s.overflowY) && r.bottom>b.bottom+1)return false;}return true })()'), 'terminal grid fits its clipping ancestors')
  for (const [width, height] of [[480, 340], [1100, 720]]) {
    win.setSize(width, height)
    await delay(100)
    await js('showContextMenu(innerWidth - 12, innerHeight - 12); openSubmenu()')
    const bounds = await js('(() => { const r = ctxSubMenu.getBoundingClientRect(); return { top: r.top, bottom: r.bottom, left: r.left, right: r.right, height: innerHeight, width: innerWidth } })()')
    assert.ok(bounds.top >= 0 && bounds.bottom <= bounds.height && bounds.left >= 0 && bounds.right <= bounds.width, `submenu fits ${width}x${height}`)
  }
  await js('hideContextMenu(); leaveTerminal()')
  assert.equal(await js('currentView'), 'list')
  await js('openProfilePicker(getTool("copilot"))')
  win.webContents.send('install:progress', {toolId:'copilot',profileId:'default',percent:42,line:'Downloading packages',elapsedSeconds:8})
  await delay(50)
  assert.match(await js('profileStatus.textContent'), /42%/)
  assert.equal(await js('profileInstall.textContent'), 'CANCEL')
  win.webContents.send('install:done', {toolId:'copilot',profileId:'default',ok:true,installed:true})
  await delay(50)
  assert.equal(await js('profileInstall.textContent'), 'UPDATE')
  assert.match(await js('profileStatus.textContent'), /ready/)
  await js('closeProfilePicker(true)')
  await js('openProfilePicker(getTool("codex"))')
  await delay(100)
  assert.equal(await js('profileList.children.length'), 1)
  assert.equal(await js('profileOpen.disabled'), false, 'installed profile has a visible OPEN action')
  assert.match(await js('profileHint.textContent'), /OPEN/)
  await fs.writeFile(path.join(outputDir, 'profiles.png'), (await win.webContents.capturePage()).toPNG())
  const { DatabaseSync } = require('node:sqlite')
  const databasePath = path.join(root, 'system/Codex/Profiles/Default/.codex/state_5.sqlite')
  await fs.mkdir(path.dirname(databasePath), { recursive: true })
  const database = new DatabaseSync(databasePath)
  database.exec("CREATE TABLE sessions (id TEXT); INSERT INTO sessions VALUES ('shared-session')")
  database.close()
  assert.equal((await js('window.api.updateProfileSettings("codex", "default", {sharedSessions: true})')).ok, true)
  await js('closeProfilePicker(true); openTerminal(getTool("codex"))')
  await js('leaveTerminal()')
  const shared = new DatabaseSync(path.join(root, 'system/Codex/_shared/sharedSessions/.codex/state_5.sqlite'), { readOnly: true })
  try { assert.equal(shared.prepare('SELECT id FROM sessions').get().id, 'shared-session') } finally { shared.close() }
  const secondary = await js('window.api.createProfile("codex", "Second window", {})')
  assert.equal(secondary.profile.installed, true, 'new profiles use the existing Codex installation')
  await js('openTerminal(getTool("codex"))')
  const parentSession = await js('activeSessionId')
  await js(`openProfilePicker(getTool('codex'), ${JSON.stringify(secondary.profile.id)}, 'switch');`)
  await js('openSelectedProfile()')
  let extra
  for(let attempt=0;attempt<100;attempt++) {
    extra=BrowserWindow.getAllWindows().find(w=>w.id!==win.id)
    if(extra && await extra.webContents.executeJavaScript('typeof terminal !== "undefined" && activeSessionId !== null && terminal.buffer.active.getLine(0)?.translateToString().includes("OMNISHELL_TEST_READY")').catch(()=>false)) break
    await delay(30)
  }
  assert.ok(extra,'Switch CLI creates an auxiliary window')
  assert.equal(await js('activeSessionId'),parentSession,'original session is preserved')
  assert.equal(await extra.webContents.executeJavaScript('isAuxiliaryWindow'),true)
  await extra.webContents.executeJavaScript('window.api.ptyWrite("done" + String.fromCharCode(13))')
  for(let attempt=0;attempt<100 && !await extra.webContents.executeJavaScript('terminalExited');attempt++) await delay(30)
  assert.equal(extra.isDestroyed(),false,'auxiliary window remains available after its CLI exits')
  assert.match(await extra.webContents.executeJavaScript('Array.from({length:terminal.rows},(_,i)=>terminal.buffer.active.getLine(i)?.translateToString()).join("\\n")'), /Session ended \/ exit 0/)
  extra.webContents.executeJavaScript('window.api.closeWindow()')
  for(let attempt=0;attempt<100 && !extra.isDestroyed();attempt++) await delay(30)
  assert.equal(extra.isDestroyed(),true,'auxiliary window closes through the animated window action')
  await js('window.api.ptyWrite("done" + String.fromCharCode(13))')
  for(let attempt=0;attempt<100 && !await js('terminalExited');attempt++) await delay(30)
  assert.equal(await js('currentView'),'terminal')
  assert.match(await js('Array.from({length:terminal.rows},(_,i)=>terminal.buffer.active.getLine(i)?.translateToString()).join("\\n")'), /Session ended \/ exit 0/)
  await js('leaveTerminal()')
  assert.equal(await js('currentView'),'list')
  win.setSize(480,340)
  await delay(100)
  await js('selectTool("kimi",true)')
  await delay(240)
  assert.ok(await js('(() => { const r=rows.get("kimi").item.getBoundingClientRect(),g=listScroll.getBoundingClientRect(); return r.top>=g.top-1 && r.bottom<=g.bottom+1 })()'), 'keyboard navigation reveals the last item in a short window')
  const defaultDocument = path.join(root, 'system/Codex/Profiles/Default/Default-Codex.Toml')
  assert.ok((await fs.readFile(defaultDocument, 'utf8')).includes('id = "default"'), 'Default has its own TOML')
  const created = await js('window.api.createProfile("codex", "İş", {sharedSkills: false, sharedMcp: false})')
  assert.equal(created.ok, true)
  await js('openProfilePicker(getTool("codex"))')
  await js(`setSelectedProfile(${JSON.stringify(created.profile.id)}); showProfileSettings(); profileSettingsDraft.sharedSkills = true`)
  win.setSize(1100, 720)
  await delay(100)
  assert.equal(await js('profileList.scrollHeight <= profileList.clientHeight + 1'), true, 'two profiles stay visible without an inner scrollbar')
  await fs.writeFile(path.join(outputDir, 'profile-settings.png'), (await win.webContents.capturePage()).toPNG())
  assert.equal(await js('profileSettingsDraft.sharedSkills'), true)
  await js('setSelectedProfile("default")')
  assert.equal(await js('profileSettingsDraft'), null, 'switching profiles discards stale settings draft')
  assert.equal(await js('profileSettings.classList.contains("hidden")'), true)
  await js('closeProfilePicker(true)')
  const customRoot = path.join(root, 'system/Codex/Profiles/İş')
  assert.ok((await fs.readFile(path.join(customRoot, 'İş-Codex.Toml'), 'utf8')).includes('shared_mcp = false'))
  await fs.mkdir(path.join(customRoot, '.codex/skills/private'), { recursive: true })
  await fs.writeFile(path.join(customRoot, '.codex/skills/private/SKILL.md'), 'private skill')
  const configFor = (directory) => `[mcp_servers.private]\ncommand = ${JSON.stringify(path.join(directory, 'mcp.js'))}\n`
  const sharedConfig = path.join(root, 'system/Codex/_shared/sharedConfig/.codex/config.toml')
  const otherConfig = path.join(root, 'system/Codex/Profiles/Second window/.codex/config.toml')
  await fs.writeFile(path.join(customRoot, '.codex/config.toml'), configFor(customRoot))
  await fs.mkdir(path.dirname(sharedConfig), { recursive: true })
  await fs.writeFile(sharedConfig, configFor(customRoot))
  await fs.mkdir(path.dirname(otherConfig), { recursive: true })
  await fs.writeFile(otherConfig, configFor(customRoot))
  assert.equal((await js(`window.api.createProfile("codex", "İŞ", {})`)).ok, false, 'case-insensitive duplicate is rejected')
  assert.equal((await js(`window.api.createProfile("codex", "CON", {})`)).ok, false, 'reserved Windows name is rejected')
  const renamed = await js(`window.api.renameProfile("codex", ${JSON.stringify(created.profile.id)}, "Proje")`)
  assert.equal(renamed.ok, true)
  const renamedRoot = path.join(root, 'system/Codex/Profiles/Proje')
  assert.ok((await fs.readFile(path.join(renamedRoot, 'Proje-Codex.Toml'), 'utf8')).includes('name = "Proje"'))
  assert.equal(await fs.readFile(path.join(renamedRoot, '.codex/skills/private/SKILL.md'), 'utf8'), 'private skill')
  assert.equal(await fs.readFile(path.join(renamedRoot, '.codex/config.toml'), 'utf8'), configFor(renamedRoot))
  assert.equal(await fs.readFile(sharedConfig, 'utf8'), configFor(renamedRoot))
  assert.equal(await fs.readFile(otherConfig, 'utf8'), configFor(renamedRoot))
  assert.equal(fsSync.existsSync(customRoot), false)
  const caseRenamed = await js(`window.api.renameProfile("codex", ${JSON.stringify(created.profile.id)}, "PROJE")`)
  assert.equal(caseRenamed.ok, true)
  const caseRoot = path.join(root, 'system/Codex/Profiles/PROJE')
  assert.ok((await fs.readFile(path.join(caseRoot, 'PROJE-Codex.Toml'), 'utf8')).includes('name = "PROJE"'))
  assert.equal((await fs.readdir(caseRoot)).filter((name) => name.toLowerCase().endsWith('.toml')).join(','), 'PROJE-Codex.Toml')
  assert.equal(await fs.readFile(path.join(caseRoot, '.codex/skills/private/SKILL.md'), 'utf8'), 'private skill')
  assert.equal((await js(`window.api.renameProfile("codex", ${JSON.stringify(created.profile.id)}, "Proje")`)).ok, true)
  let previousRoot = renamedRoot
  for (let index = 0; index < 4; index += 1) {
    const nextName = `Trial-${randomUUID().slice(0, 8)}`
    const result = await js(`window.api.renameProfile("codex", ${JSON.stringify(created.profile.id)}, ${JSON.stringify(nextName)})`)
    assert.equal(result.ok, true, `random rename ${index + 1}: ${result.error || ''}`)
    const nextRoot = path.join(root, 'system/Codex/Profiles', nextName)
    assert.equal(await fs.readFile(path.join(nextRoot, '.codex/config.toml'), 'utf8'), configFor(nextRoot))
    assert.equal(await fs.readFile(sharedConfig, 'utf8'), configFor(nextRoot))
    assert.equal(await fs.readFile(otherConfig, 'utf8'), configFor(nextRoot))
    assert.equal(fsSync.existsSync(previousRoot), false)
    assert.equal((await fs.readdir(nextRoot)).filter((name) => name.endsWith('-Codex.Toml')).join(','), `${nextName}-Codex.Toml`)
    previousRoot = nextRoot
  }
  assert.equal((await js(`window.api.renameProfile("codex", ${JSON.stringify(created.profile.id)}, "Proje")`)).ok, true)
  const originalRename = fs.rename
  let failedWrite
  fs.rename = async (from, to) => {
    if (to === sharedConfig) throw Object.assign(new Error('simulated configuration lock'), { code: 'EACCES' })
    return originalRename(from, to)
  }
  try { failedWrite = await js(`window.api.renameProfile("codex", ${JSON.stringify(created.profile.id)}, "Blocked")`) }
  finally { fs.rename = originalRename }
  assert.equal(failedWrite.ok, false)
  assert.match(failedWrite.error, /previous name was restored/)
  assert.equal(await fs.readFile(path.join(renamedRoot, '.codex/config.toml'), 'utf8'), configFor(renamedRoot))
  assert.equal(await fs.readFile(sharedConfig, 'utf8'), configFor(renamedRoot))
  assert.equal(await fs.readFile(otherConfig, 'utf8'), configFor(renamedRoot))
  assert.equal(fsSync.existsSync(path.join(root, 'system/Codex/Profiles/Blocked')), false)
  const validConfig = await fs.readFile(path.join(renamedRoot, '.codex/config.toml'))
  await fs.writeFile(path.join(renamedRoot, '.codex/config.toml'), Buffer.from([0xff]))
  const failedRename = await js(`window.api.renameProfile("codex", ${JSON.stringify(created.profile.id)}, "Blocked")`)
  assert.equal(failedRename.ok, false)
  assert.match(failedRename.error, /previous name was restored/)
  assert.equal((await js(`window.api.profiles("codex")`)).profiles.find((profile) => profile.id === created.profile.id).name, 'Proje')
  assert.equal(fsSync.existsSync(renamedRoot), true)
  await fs.writeFile(path.join(renamedRoot, '.codex/config.toml'), validConfig)
  const deleted = await js(`window.api.deleteProfile("codex", ${JSON.stringify(created.profile.id)})`)
  assert.equal(deleted.ok, true)
  assert.equal(fsSync.existsSync(renamedRoot), false)
  assert.equal(await fs.readFile(path.join(deleted.recoverablePath, 'Proje-Codex.Toml'), 'utf8').then((value) => value.includes('name = "Proje"')), true)
  assert.equal(await fs.readFile(path.join(deleted.recoverablePath, '.codex/skills/private/SKILL.md'), 'utf8'), 'private skill')
  assert.deepEqual(errors, [])
  console.log('PASS Electron: real ConPTY, repeated profile renames and rollback, private TOML data, Switch CLI, SQLite sharing')
  clearTimeout(timeout)
  win.destroy()
  await delay(250)
  await fs.rm(root, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }).catch(() => {})
  app.quit()
})().catch(async (error) => {
  console.error(error)
  clearTimeout(timeout)
  for (const win of BrowserWindow.getAllWindows()) {
    await win.webContents.executeJavaScript('window.api.terminalStop()').catch(() => {})
  }
  app.exit(1)
})
